---
collections:
  - name: ansible.windows
    version: 2.3.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.controller
    version: 4.5.0
  - name: amazon.aws
    version: 7.2.0
  - name: servicenow.itsm
    version: 2.4.0
  - name: community.general
    version: 8.1.0
  - name: zjleblanc.reporting
    version: ">=1.3.0"
...
