---
collections:
  - name: ansible.windows
  - name: chocolatey.chocolatey
  - name: community.windows
  - name: community.general
  - name: amazon.aws
  - name: ansible.posix
  - name: community.aws
    version: "6.1.0"
  - name: servicenow.itsm
  - name: awx.awx
...
