---
collections:
  - name: ansible.windows
  - name: ansible.posix
  - name: ansible.controller
  - name: amazon.aws
  - name: servicenow.itsm
  - name: community.windows
  - name: community.general
  - name: community.aws
  - name: zjleblanc.reporting
    version: ">=1.3.0"
...
