# Using a credential to set these
# MAILHOST: smtp.office365.com
# MAILHOST_PORT: 587
# MAILHOST_USERNAME: mickey.mouse@exmaple.com
# MAILHOST_PASSWORD: 123456
my_server: null
mailfrom: mickey.mouse@exmaple.com (Mickey Mouse)
mailto:
- Mickey Mouse <mickey.mouse@exmaple.com>
- Donald Duck <donald.duck@example.com>
bccto:
- Mickey Mouse <mickey.mouse@exmaple.com>
- Donald Duck <donald.duck@example.com>