---
authors:
  - Eric Ames (ericcames)
dependencies:
  "ansible.windows": ">=3.2.0"
  "amazon.aws": ">=7.2.0"
  "ansible.posix": ">=2.1.0"
  "ansible.utils": ">=6.0.0"
  "ansible.platform": ">=2.6.20250924"
  "ansible.hub": ">=1.0.2"
  "ansible.controller": ">=4.7.1"
  "ansible.eda": ">=2.10.0"
  "infra.aap_configuration": ">=3.8.0"
  "servicenow.itsm": ">=2.13.0"
  "community.general": ">=11.4.0"
  "community.windows": ">=3.0.1"
license_file: LICENSE
name: windows_daily_demo
description: Build a stand alone webserver with custom content.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/aap.dailydemo.windows
issues: https://github.com/ericcames/aap.dailydemo.windows/issues
tags:
  - lab
  - cloud
  - amazon
  - aws
  - windows
  - dailydemo
  - ansible
  - automation
  - sales
version: 1.0.0