---
controller_templates:
  - name: Delete Daily Demo Windows
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: amazon_aws_ee
    project: aap.dailydemo.windows
    playbook: playbooks/site_delete.yml
    ask_tags_on_launch: false
    job_tags: remove
    credentials:
      - "{{ my_aap_credential }}"
      - "{{ my_aws_credential }}"
    extra_vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: DDW - Network Create
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: amazon_aws_ee
    project: aap.dailydemo.windows
    playbook: playbooks/01_create_vpc.yml
    job_tags: create
    credentials:
      - "{{ my_aws_credential }}"

  - name: DDW - VM Create
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: amazon_aws_ee
    project: aap.dailydemo.windows
    playbook: playbooks/02_create_instance.yml
    job_tags: create
    credentials:
      - "{{ my_aws_credential }}"
      - Daily Demo Windows

  - name: DDW - Create Incident
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.windows
    playbook: playbooks/servicenow/incident_create.yml
    credentials:
      - ServiceNow ITSM Credential
    extra_vars:
      caller_name: "{{ my_snow_caller_name }}"
