---
controller_credentials:
  - name: Daily Demo Windows - Ames
    organization: "{{ my_organization }}"
    credential_type: Machine
    inputs:
      password: "{{ ddw_password }}"
      username: "{{ ddw_username }}"
      become_method: runas
      become_username: administrator

  - name: ServiceNow ITSM Credential - Ames
    description: ServiceNow ITSM Credential
    organization: "{{ my_organization }}"
    credential_type: ServiceNow ITSM Credential
    inputs:
      instance: "{{ snow_url }}"
      username: "{{ snow_username }}"
      password: "{{ servicenow_passwd }}"
