---
controller_credential_types:
- name: ServiceNow ITSM Credential
  description: ServiceNow ITSM Credential
  inputs:
    fields:
    - id: instance
      type: string
      label: Instance
    - id: username
      type: string
      label: username
    - id: password
      type: string
      label: password
      secret: true
    required:
    - instance
    - username
    - password
  injectors:
    env:
      SN_HOST: !unsafe '{{instance}}'
      SN_PASSWORD: !unsafe '{{password}}'
      SN_USERNAME: !unsafe '{{username}}'
