- name: Include our user info
  ansible.builtin.include_vars:
    file: files/{{ windows_account_create_user_list_vault }}

- name: Relax password complexity requirements
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

- name: Create the users directory structure
  loop: "{{ users }}"
  no_log: true
  ansible.windows.win_file:
    path: c:\Users\{{ item['name'] }}
    state: directory

- name: Create local user accounts
  loop: "{{ users }}"
  no_log: false
  ansible.windows.win_user:
    name: "{{ item['name'] }}"
    password: "{{ item['user_password'] }}"
    state: present
    groups: "{{ item['groups'] }}"
    home_directory: c:\Users\{{ item['name'] }}
    password_never_expires: true
    update_password: "on_create"
    user_cannot_change_password: true
