---
- name: Install IIS Webserver
  ansible.windows.win_feature:
    name: Web-Server
    state: present

- name: Reboot if installing Web-Server feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: Template simple web site to iis_site_path as index.html
  ansible.windows.win_template:
    src: 'index.html.j2'
    dest: C:\inetpub\wwwroot\index.html

- name: Copy a AAP Logo
  ansible.windows.win_copy:
    src: images/aap.png
    dest: C:\inetpub\wwwroot\aap.png

- name: Copy QNRCode
  ansible.windows.win_copy:
    src: images/AmesQNRCode.png
    dest: C:\inetpub\wwwroot\AmesQNRCode.png

- name: Show website addresses
  loop:
    - http://{{ inventory_hostname }}
  ansible.builtin.debug:
    msg: "{{ item }}"
