---
- name: Disable the SMB Server
  register: my_output
  ansible.windows.win_powershell:
    script: |
      Set-SmbServerConfiguration -EnableSMB1Protocol $false

- name: Print the SMB Server Configuration
  ansible.builtin.debug:
    msg: "{{ my_output.output }}"
