---
- name: Check for our mandatory variables
  # You can create a custom credential for the mandatory variables
  ansible.builtin.assert:
    that:
      - MAILHOST is defined
      - MAILHOST_PORT is defined
      - MAILHOST_USERNAME is defined
      - MAILHOST_PASSWORD is defined
    fail_msg: "Please make sure your mandatory variables are set"
    success_msg: "All mandatory variables have beed set"

- name: Send an email with the link to the aap demo Server
  community.general.mail:
    host: "{{ MAILHOST }}"
    port: "{{ MAILHOST_PORT }}"
    secure: try
    username: "{{ MAILHOST_USERNAME }}"
    password: "{{ MAILHOST_PASSWORD }}"
    subject: Ansible Automation Platform (AAP) Daily Demo - Windows
    body: "System {{ my_server }} has been successfully provisioned using AAP.\n
          The playbooks and notes can be found here: https://github.com/ericcames/aap.dailydemo.windows\n
          The following address http://{{ my_server }} will take you to a custom website.\n
          The server will be destroyed at 01:15 AM UTC time.\n
          Remote Desktop is enabled; Ansible-r0cks!\n"
    from: "{{ mailfrom }}"
    to: "{{ mailto }}"
    bcc: "{{ bccto }}"
