---
- name: So that we know why we built the thing
  register: my_result
  servicenow.itsm.api:
    action: post
    resource: "{{ create_cmdb_relationship_resource }}"
    data:
      child: "{{ create_cmdb_relationship_child }}"
      parent: "{{ get_instance_info_server }}"
      type: "{{ create_cmdb_relationship_type }}"

- name: Print the result
  ansible.builtin.debug:
    var: my_result
