---
- name: Checking the SMB Server Configuration
  register: my_output
  changed_when: false
  ansible.windows.win_powershell:
    script: |
      Get-SmbServerConfiguration | Select EnableSMB1Protocol

- name: Print the SMB Server Configuration
  ansible.builtin.debug:
    msg: "{{ my_output.output }}"
