---
- name: Create the devops directory structure
  ansible.windows.win_file:
    path: 'c:\Users\devops'
    state: directory

- name: Copy the powershell patch report script into place
  ansible.windows.win_copy:
    src: scripts/patch_report
    dest: 'c:\Users\devops\patch_report'

- name: Run PowerShell patch report script
  ansible.windows.win_powershell:
    script: 'c:\Users\devops\patch_report'

- name: Get file content
  register: my_content
  ansible.windows.win_shell: 'type C:\Users\devops\ScriptLog.txt'

- name: Print file content
  ansible.builtin.debug:
    msg: "{{ my_content.stdout_lines }}"
