---
- name: Run PowerShell patch report script
  register: my_output
  changed_when: false
  ansible.windows.win_powershell:
    script: |
      $DotNetVersions = Get-ChildItem HKLM:\SOFTWARE\WOW6432Node\Microsoft\Updates | Where-Object {$_.name -like
        "*.NET Framework*"}

      ForEach($Version in $DotNetVersions){

      $Updates = Get-ChildItem $Version.PSPath
          $Version.PSChildName
          ForEach ($Update in $Updates){
              $Update.PSChildName
              }
      }

- name: Microsoft .Net Patches
  ansible.builtin.debug:
    msg: "{{ my_output.output }}"
