---
- name: Provisioning user local access
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986

  tasks:

    - name: Relax password complexity requirements
      community.windows.win_security_policy:
        section: System Access
        key: PasswordComplexity
        value: 0

    - name: Create the devops directory structure
      ansible.windows.win_file:
        path: 'c:\Users\devops'
        state: directory

    - name: Create local user accounts
      ansible.windows.win_user:
        name: devops
        password: "{{ devops_password }}"
        state: present
        groups:
          - Users
          - Remote Desktop Users
          - Administrators
        home_directory: 'c:\Users\devops'
        password_never_expires: true
        update_password: "on_create"
        user_cannot_change_password: true
...
